### PR TITLE
Add 18 psi-ms.obo files from v4.1.34 to v4.1.51 released on 2021/3/27

### PR DESCRIPTION
**Pull request by ZhixuNi**
Hi!

I've just added 18 psi-ms.obo files from v4.1.34 to v4.1.51 to the obo folder.
I've just tested with ProteoWizard 3.0.21101.e1b2cc25b I downloaded today.
mzML from ProteoWizard 3.0.21101.e1b2cc25b seems using  psi-ms.obo v4.1.41
So I think this obo update might be enough for year 2021.

I did not make any other changes, please check the compatibility, thanks!

### CODE REVIEW

**Comment by MKoesters** [comment]
Hi @ZhixuNi,

Thanks for you contribution!

We (the developers) just discussed your PR.
Since we have aggregated quite some obo files, we thought it would be better to supply a script, which can download the matching (or most recent) obo file from a git with tagged versions so you have your obo files only locally but not in the repo.
This would mean, that in future it wouldn't be necessary to add obos to the git and bloat the repo.

However I need to see when I'll have time to implement this and if it makes sense to add the new obo files in the mean time.

I'm also happy to hear other options, if you have an opinion on that! :)

Best,
Manuel

**Comment by ZhixuNi** [comment]
A script is a good idea @MKoesters!
The obo files in this PR were collected by clone the HUPO repo: https://github.com/HUPO-PSI/psi-ms-CV
Then collect the `psi-ms.obo` file in the `master` branch from each commit, and rename it according to the version info inside the obo file. 
Sometimes there are multiple commits that claim the same psi-ms.obo versions, then I took the latest one.

I hope this may help you to develop the scripts. 
It would be nice to have a function in pymzML to check/update the obo files as well.

**Comment by MKoesters** [comment]
Auto download of missing obo files will be implemented by #266

**Comment by ZhixuNi** [comment]
@MKoesters The new auto download function looks nice :+1:  You can close this PR I think. I hope no more issues from obo updates :smile:

**Pull request closed without merging**
