### PR TITLE
Fix tests and bump version to 0.7.10

### PR DESCRIPTION
**Pull request by RJMW**

### CODE REVIEW

**Comment by RJMW** [comment]
@JB-MS @MKoesters Please, can you review the changes and upload the new version to pip

**Comment by JB-MS** [comment]
Good to go from my side.

Thanks for the contribution!

**Comment by MKoesters** [comment]
Yes, good to go for me too

**Comment by JB-MS** [comment]
PyPI has been updated with 0.7.10.

@RJMW Can you please test if everything works now for you?

**Comment by RJMW** [comment]
@JB-MS @MKoesters 

Yes, all working. Many thanks!

P.S. It might be useful to include each releases in the [github release section](https://github.com/pymzml/pymzML/releases). This makes it easier to trace back what release belongs to what commit, etc.

**Pull request merged**
