### PR TITLE
Upgrade oboTranslator to handle different versions of psi-ms.obo

### PR DESCRIPTION
**Pull request by myw**
Upgrade psi-ms.obo

### CODE REVIEW

**Comment by fu** [comment]
Hi myw! 
Thanks for the contribution! I like but merge your request but it would break legacy code.

For example:
```bash
$ ./_queryOBO.py 1000016                                                                           
New OBO
scan start time
Old OBO
scan time
```

My suggestion is to have a obo_version keyword at the Reader.__init__ level, which is set to 1.1.0 by default and you could change this keyword.

An even better way could be to quickly check the version of the obo used to encode the mzML similar to how we check the encoding of the mzML
```python
encodingPattern = re.compile(
    b'encoding="(?P<encoding>[A-Za-z0-9-]*)"'
)
```
Either way would be fine. What do you think ?

**Comment by myw** [comment]
I like the latter. I don't think consumers should be responsible for
picking a version—only overriding it if they need to.

I'm about to be gone for two weeks, but I can make the changes when I
return! You could also use the pull request as a basis and then pull in
your changes as well.

When I get back, I'll also submit code that fixes some weird behavior with
SRM Mzml Files  that I have found.

On Friday, August 28, 2015, Christian Fufezan <notifications@github.com>
wrote:

> Hi myw!
> Thanks for the contribution! I like but merge your request but it would
> break legacy code.
>
> For example:
>
> $ ./_queryOBO.py 1000016
> New OBO
> scan start time
> Old OBO
> scan time
>
> My suggestion is to have a obo_version keyword at the Reader.*init*
> level, which is set to 1.1.0 by default and you could change this keyword.
>
> An even better way could be to quickly check the version of the obo used
> to encode the mzML similar to how we check the encoding of the mzML
>
> encodingPattern = re.compile(
>     b'encoding="(?P<encoding>[A-Za-z0-9-]*)"'
> )
>
> Either way would be fine. What do you think ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pymzml/pymzML/pull/28#issuecomment-135766513>.
>


-- 
Misha (Mobile)

**Comment by myw** [comment]
So, it turns out this is more involved than we originally thought. The `psi-ms.obo` file has actually been updated frequently. The file I added as psi-ms.obo-1.2 is not actually version 1.2: it's version 3.78.0! You can examine the OBO changelog in the [psidev cvs repo](http://psidev.cvs.sourceforge.net/viewvc/psidev/psi/psi-ms/mzML/controlledVocabulary/psi-ms.obo?view=log) to see how it has evolved since the last versions you added to pymzml.

The frequent changes in the OBO that do not coincide with the evolution of the mzML standard itself present a problem for pymzml. This problem has two prongs:

1. pymzml needs to have access to all of the versions of the OBO. I can see three ways to accomplish this, none of which are very pretty:
   a. download every numbered version of the OBO and add it to the pymzml obo folder manually
      - lots of extra files and hassle
      - potential need for manual or semi-manual curation
      - have to do this process again every time a new OBO version comes out
      - amounts to a flat, silly version of what a versioning system is supposed to do for you, which is unsatisfying
     - can make this into a script to minimize some of the pain

   b. download the appropriate OBO version anew every time a `Reader` object is created
      - slow; adds a very slow step to an already potentially slow process (when reading many mzML files)
      - adds a connectivity dependency to the library; it won't work if you're not online

   c. just like a., but instead of many flat files, keep the OBO versions in a single file, versioned using some kind of database, archive or version control library
      - slower than a.
      - more work and fragility than a.
      - cleaner than a.

   Of all the above options, a. seems like the least bad to me, so I'll start there.
2.  Some mzML files will specify exactly what version of the OBO they are using. Some will not. In the case that an OBO version is not specified in the mzML file itself, pymzml needs to specify its default behavior. I think that the only consistent default behavior for pymzml is to use the most recent OBO version, since the OBO is constantly evolving and correcting mistakes, adding terms, etc. Code that depends on legacy OBOs but does not specify a version (or reads from an mzML file that does not specify the OBO version) is incorrect—there's no way to know what OBO version it depends on, and since the newest OBO is the most valid one, code that depends on entries in the OBO that have been renamed is not correct. Of course, for backwards compatibility, you'd need to specify a version.
This means that the use case you presented above as an issue with queryOBO (_scan time_ being renamed to _scan start time_) actually exhibits correct default behavior when an OBO version is not specified. For any mzML files that _do_ specify the version, we could, of course, parse out the version information and load that version automatically.

Please let me know what you think about this.

**Comment by myw** [comment]
The most recent changes update the OBO database to include all of the numbered versions, and have the Reader object automatically set the OBO version if it can; if it can't, it defaults to the newest one. An option is available to specify the version at reader instantiation.

I've also added a script (`download_obo_database.py`) to automatically download and store all the OBO versions, and unit tests for the `oboTranslator` and `Reader` classes that specify this behavior (along with existing untested behavior).

My next pull request, which will be rebased on this one, will help with proper parsing of SRM mzML files, which currently cause problems for pymzml because they contain `<chromatogram>` tags that are not inside `<chromatogramList>` tags.

**Comment by fu** [comment]
Hi Misha,

I'll have a look asap, sorry for not answering, but I was off the grid. 
Anywhays, thanks for the input, I am on it starting from tomorrow!

Cheers

.c

**Comment by myw** [comment]
Turns out the parsing works, despite the unexpected tags; it nests a little weird, but at least all the data gets pulled in; with the modified OBO, this now works for our purposes, so this is the only pull request I'm making for now.

**Comment by fu** [comment]
Thanks a lot Misha! 
Merged your excellent work into the project. Thanks for using and making pymzml better.

Cheers

.c

**Pull request merged**
